#!/usr/bin/env python3
"""spv2h.py in.spv out.h NAME — SPIR-V -> C header (uint32_t массив).
Использование: .codeSize = NAME_N * 4, .pCode = NAME
"""
import struct, sys

spv, out, name = sys.argv[1], sys.argv[2], sys.argv[3].upper()
data = open(spv, 'rb').read()
assert len(data) % 4 == 0
assert struct.unpack_from('<I', data, 0)[0] == 0x07230203, 'not SPIR-V'
dws = struct.unpack('<%dI' % (len(data) // 4), data)
with open(out, 'w') as f:
    f.write('/* auto-generated by spv2h.py from %s */\n' % spv)
    f.write('#ifndef %s_H\n#define %s_H\n' % (name, name))
    f.write('static const uint32_t %s[] = {\n' % name)
    for i in range(0, len(dws), 8):
        f.write('   ' + ' '.join('0x%08xu,' % d for d in dws[i:i+8]) + '\n')
    f.write('};\nstatic const uint32_t %s_N = %d; /* dwords */\n'
            % (name, len(dws)))
    f.write('#endif\n')
print('%s: %d dwords (%d bytes)' % (out, len(dws), len(data)))
