#!/usr/bin/env python3
"""Generate C arrays of format compatibility lists from vkd3d-proton sources.

Sources (both tables are static, so the enumeration is exact by construction):
  libs/vkd3d/utils.c: vkd3d_formats[]                  - DXGI -> VkFormat map
  libs/vkd3d/utils.c: dxgi_format_compatibility_list[] - lists for mutable images

The probe is needed for one question: a sparse resource in vkd3d is exactly
CreateReservedResource (resource.c: heap_properties = RESERVED ? NULL : &resource->heap_properties,
so sparse_resource = !heap_properties is true only for reserved). For a reserved
resource vkd3d builds the list from format_compatibility_lists[Format] and sets
MUTABLE_FORMAT_BIT if the list has >= 2 formats (resource.c:
vkd3d_get_format_compatibility_list, "if (list->format_count < 2) return false;").
So MUTABLE + list go together, and the question reduces to one: which of these
lists will the turnip driver accept together with SPARSE_RESIDENCY.

Usage: gen-vkd3d-lists.py /path/to/vkd3d-proton > lists.h
"""
import re
import sys

VK_FMT = re.compile(r"VK_FORMAT_[A-Z0-9_]+")


def parse_format_map(text):
    """{DXGI_FORMAT_X: VK_FORMAT_Y} from the vkd3d_formats[] table."""
    out = {}
    for m in re.finditer(r"\{(DXGI_FORMAT_[A-Z0-9_]+),\s*(VK_FORMAT_[A-Z0-9_]+)", text):
        out.setdefault(m.group(1), m.group(2))
    return out


def parse_compat_lists(text, fmap):
    """Classes with >= 2 formats: [(dxgi, [vk, ...]), ...] in table order."""
    body = text[text.index("dxgi_format_compatibility_list[] ="):]
    body = body[: body.index("\n};")]
    # entry: {DXGI_FORMAT_X,\n {A, B, C},\n ...} - the first field is image_format,
    # the second is the list of view_formats, the rest (uint/typeless) are of no interest.
    entries = []
    for m in re.finditer(
        r"\{(DXGI_FORMAT_[A-Z0-9_]+),\s*\{([^}]*)\}", body
    ):
        dxgi, views = m.group(1), m.group(2)
        dxf = [v.strip() for v in views.split(",") if v.strip() and "UNKNOWN" not in v]
        # list = the image_format itself + all view_formats (resource.c: add_format(image) then the loop)
        full = [dxgi] + dxf
        vks, seen = [], set()
        for d in full:
            vk = fmap.get(d)
            if vk and vk not in seen:
                seen.add(vk)
                vks.append(vk)
        if len(vks) >= 2:  # otherwise MUTABLE is not set at all
            entries.append((dxgi, vks))
    return entries


def main():
    root = sys.argv[1] if len(sys.argv) > 1 else "/var/home/armada/opencode/srcs/vkd3d-proton"
    text = open(root + "/libs/vkd3d/utils.c", encoding="utf-8", errors="replace").read()
    fmap = parse_format_map(text)
    entries = parse_compat_lists(text, fmap)

    cap = 8
    trunc = [d for d, v in entries if len(v) > cap]
    if trunc:
        # Silently truncating is not allowed: a lost format would make the conclusion false.
        sys.exit("List longer than %d in: %s" % (cap, ", ".join(trunc)))

    print("/* Generated by scripts/gen-vkd3d-lists.py from %s - do not edit by hand. */" % root)
    print("#define VKD3D_MUTABLE_CLASS_COUNT %d" % len(entries))
    print("struct vkd3d_fmt_class { const char *dxgi; VkFormat f[%d]; unsigned int n; };" % cap)
    print("static const struct vkd3d_fmt_class vkd3d_fmt_classes[] = {")
    for dxgi, vks in entries:
        print('    { "%s", { %s }, %d },'
              % (dxgi.replace("DXGI_FORMAT_", ""), ", ".join(vks), len(vks)))
    print("};")
    sys.stderr.write("classes with >=2 formats: %d (max list length %d)\n"
                     % (len(entries), max(len(v) for _, v in entries)))


if __name__ == "__main__":
    main()
